version: '3.8'

services:
  mariadb:
    image: mariadb:11.2
    container_name: mariadb-payment-gateway
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodbtimeout=10"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
