version: '3.8'

services:
  mariadb:
    image: mariadb:11.2
    container_name: mariadb-payment-gateway
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: payment_gateway
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodbtimeout=10"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
